Repository novasamatech/parity-signer, pull requests merged in 2019-07, with the labels that each got.

#259 Update screenshot and add MyCrypto reference
  README.md
  docs/screenshots.jpg
Labels: A2-insubstantial, M3-docs

#274 chore(): bump 222
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A2-insubstantial

#272 fix: padding when keyboard is visible
  package.json
  src/screens/AccountNew.js
  src/screens/AccountRecover.js
  yarn.lock
Labels: A0-pleasereview

#275 fix: refactor the network list and add lodash
  package.json
  src/components/AccountCard.js
  src/components/AccountDetailsCard.js
  src/components/AccountIconChooser.js
  src/components/NetworkButton.js
  src/constants.js
  src/screens/AccountNetworkChooser.js
  src/screens/AccountNew.js
  src/screens/AccountRecover.js
  src/stores/ScannerStore.js
  src/util/account.js
  yarn.lock
Labels: A1-onice

#281 fix: rename chainId
  src/components/AccountCard.js
  src/components/AccountDetailsCard.js
  src/screens/AccountBackup.js
  src/screens/AccountDetails.js
  src/screens/AccountEdit.js
  src/screens/AccountList.js
  src/screens/AccountNetworkChooser.js
  src/screens/AccountNew.js
  src/screens/AccountRecover.js
  src/screens/MessageDetails.js
  src/screens/SignedTx.js
  src/screens/TxDetails.js
  src/stores/AccountsStore.js
  src/stores/ScannerStore.js
  src/util/account.js
  src/util/db.js
  src/util/transaction.js
Labels: A0-pleasereview

#283 Get back the icon selector
  src/components/AccountIconChooser.js
Labels: A8-looksgood

#265 Make sure the recovery phrase is emptied upon process abortion
  src/screens/AccountRecover.js
Labels: A0-pleasereview

#285 Fix unneeded permissions
  android/app/src/main/AndroidManifest.xml
Labels: A8-looksgood

#288 chore(): bump to 3.0.0
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A2-insubstantial, A8-looksgood

#287 chore(): update headers
  android/app/src/main/java/io/parity/signer/EthkeyBridge.java
  android/app/src/main/java/io/parity/signer/EthkeyBridgePackage.java
  index.android.js
  index.ios.js
  index.js
  ios/NativeSigner/EthkeyBridge.m
  ios/NativeSigner/EthkeyBridge.swift
  ios/NativeSigner/NativeSigner-Bridging-Header.h
  ios/NativeSigner/String.swift
  ios/NativeSigner/main.m
  jest-setup.js
  rust/signer/signer.h
  src/App.js
  src/colors.js
  src/components/AccountCard.js
  src/components/AccountDetailsCard.js
  src/components/AccountIcon.js
  src/components/AccountIconChooser.js
  src/components/AccountSeed.js
  src/components/Background.js
  src/components/Button.js
  src/components/Card.js
  src/components/DataDetails.js
  src/components/Header.js
  src/components/Markdown.js
  src/components/QrView.js
  src/components/SecurityHeader.js
  src/components/TextInput.js
  src/components/TxDetailsCard.js
  src/screens/About.js
  src/screens/AccountBackup.js
  src/screens/AccountDetails.js
  src/screens/AccountEdit.js
  src/screens/AccountList.js
  src/screens/AccountNetworkChooser.js
  src/screens/AccountNew.js
  src/screens/AccountPin.js
  src/screens/AccountRecover.js
  src/screens/AccountUnlock.js
  src/screens/Loading.js
  src/screens/MessageDetails.js
  src/screens/PrivacyPolicy.js
  src/screens/QrScanner.js
  src/screens/Security.js
  src/screens/SignedMessage.js
  src/screens/SignedTx.js
  src/screens/TermsAndConditions.js
  src/screens/TxDetails.js
  src/stores/AccountsStore.js
  src/stores/ScannerStore.js
  src/stores/SecurityStore.js
  src/stores/TxStore.js
  src/util/checksum.js
  src/util/checksum.spec.js
  src/util/db.js
  src/util/native.js
  src/util/transaction.js
  src/util/units.js
  src/util/units.spec.js
Labels: A0-pleasereview, A2-insubstantial

#282 Don't allow empty seed phrase recovery
  src/screens/AccountRecover.js
  src/stores/AccountsStore.js
  src/util/account.js
Labels: A0-pleasereview

#286 Security header refresh
  android/app/src/main/AndroidManifest.xml
  src/components/SecurityHeader.js
  src/screens/Security.js
  src/stores/SecurityStore.js
Labels: A0-pleasereview

#284 Refactor updateNewAccount
  package.json
  src/components/AccountIconChooser.js
  src/screens/AccountNew.js
  src/screens/AccountRecover.js
  src/stores/AccountsStore.js
  src/util/debounce.js
  yarn.lock
Labels: A0-pleasereview, A9-buythatmanabeer

#291 Fix keyboard aware scroll view related problem
  android/app/src/main/AndroidManifest.xml
  src/components/AccountSeed.js
  src/components/KeyboardScrollView.js
  src/screens/AccountNew.js
  src/screens/AccountRecover.js
Labels: A0-pleasereview

#292 fix: change button default color
  src/colors.js
  src/components/Button.js
  src/components/Header.js
  src/screens/MessageDetails.js
  src/screens/TxDetails.js
Labels: A0-pleasereview

#294 feat: Convert rawData to Uint8Array
  src/screens/QrScanner.js
Labels: A8-looksgood
