Repository novasamatech/parity-signer, pull requests merged in 2019-08, with the labels that each got.

#300 fix: enable screenshot in dev mode
  android/app/build.gradle
  android/app/src/main/java/io/parity/signer/MainActivity.java
Labels: A0-pleasereview

#296 Tbaut icon rotation
  src/components/AccountIconChooser.js
  src/components/Address.js
  src/screens/AccountNew.js
Labels: A0-pleasereview

#303 fix: disable auto complete when user input recovery phrase
  src/components/AccountSeed.js
Labels: A0-pleasereview

#304 Yarn start for react-native start preventing out of memory
  package.json
Labels: A2-insubstantial

#305 Pull react-native-secure-storage from Parity repo
  package.json
  yarn.lock
Labels: A8-looksgood

#301 Polkadot identicons
  android/app/build.gradle
  android/app/src/main/java/io/parity/signer/MainApplication.java
  android/app/src/main/res/drawable-hdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/app/src/main/res/drawable-mdpi/icon.png
  android/app/src/main/res/drawable-mdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/app/src/main/res/drawable-mdpi/node_modules_reactnavigationstack_lib_module_views_assets_backiconmask.png
  android/app/src/main/res/drawable-mdpi/src_assets_img_onboardingarrow.png
  android/app/src/main/res/drawable-xhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/app/src/main/res/drawable-xxhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/app/src/main/res/drawable-xxxhdpi/node_modules_reactnavigationstack_lib_module_views_assets_backicon.png
  android/app/src/main/res/raw/node_modules_entities_maps_entities.json
  android/app/src/main/res/raw/node_modules_reactnativevectoricons_glyphmaps_materialcommunityicons.json
  android/app/src/main/res/raw/node_modules_reactnativevectoricons_glyphmaps_materialicons.json
  android/app/src/main/res/raw/res_bip39_wordlist.json
  android/app/src/main/res/raw/res_parity_wordlist.json
  android/settings.gradle
  babel.config.js
  ios/NativeSigner.xcodeproj/project.pbxproj
  jest.config.js
  package.json
  shim.js
  src/App.js
  src/screens/AccountList.js
  yarn.lock
Labels: A8-looksgood

#308 Chore: Fix for rnpm usage
  package.json
  src/react-native.config.js
Labels: A0-pleasereview, A2-insubstantial

#310 chore: bump version of prettier
  package.json
  yarn.lock
Labels: A0-pleasereview, A2-insubstantial

#314 fix: update readme with yarn start command
  README.md
Labels: A2-insubstantial

#279 Substrate stuff in Rust
  android/app/src/main/java/io/parity/signer/EthkeyBridge.java
  ios/NativeSigner/EthkeyBridge.m
  ios/NativeSigner/EthkeyBridge.swift
  rust/signer/Cargo.lock
  rust/signer/Cargo.toml
  rust/signer/signer.h
  rust/signer/src/lib.rs
  rust/signer/src/sr25519.rs
  rust/signer/src/util.rs
  src/util/native.js
Labels: A8-looksgood

#325 UOS Qr Support (rebased on master)
  android/app/build.gradle
  android/app/src/main/assets/fonts/Manifold-CF-Bold.otf
  android/app/src/main/assets/fonts/Manifold-CF-Demi-Bold.otf
  android/app/src/main/assets/fonts/Manifold-CF-Extra-Bold.otf
  android/app/src/main/assets/fonts/Manifold-CF-Light.otf
  android/app/src/main/assets/fonts/Manifold-CF.otf
  android/app/src/main/java/io/parity/signer/MainActivity.java
  android/app/src/main/java/io/parity/signer/MainApplication.java
  android/build.gradle
  android/settings.gradle
  ios/NativeSigner.xcodeproj/project.pbxproj
  ios/NativeSigner/EthkeyBridge.swift
  ios/NativeSigner/main.m
  jest-setup.js
  jest.config.js
  package.json
  shim.js
  src/App.js
  src/components/DerivationPathField.js
  src/components/PayloadDetailsCard.js
  src/components/QrView.js
  src/console.d.ts
  src/constants.js
  src/screens/About.js
  src/screens/AccountDetails.js
  src/screens/AccountNew.js
  src/screens/AccountPin.js
  src/screens/AccountRecover.js
  src/screens/AccountUnlock.js
  src/screens/MessageDetails.js
  src/screens/QrScanner.js
  src/screens/SignedMessage.js
  src/screens/SignedTx.js
  src/screens/TxDetails.js
  src/screens/types.ts
  src/stores/AccountsStore.js
  src/stores/ScannerStore.js
  src/stores/TxStore.js
  src/util/decoders.js
  src/util/decoders.spec.js
  src/util/message.js
  src/util/native.js
  yarn.lock
Labels: A8-looksgood

#328 Parse and construct function together
  src/components/AccountIconChooser.js
  src/components/DerivationPathField.js
  src/screens/AccountNew.js
  src/screens/AccountRecover.js
  src/stores/AccountsStore.js
  src/util/keyExtract.js
  src/util/suri.js
  src/util/suri.spec.js
Labels: A0-pleasereview, A2-insubstantial, F6-refactor

#329 Add Genesis Hash
  src/constants.js
  src/util/decoders.spec.js
Labels: A8-looksgood

#331 Add genesis hash from polkadot --dev v0.5.1
  src/constants.js
  src/util/suri.js
Labels: A0-pleasereview

#336 Ethereum accountId should have a 0x
  src/util/account.js
Labels: A0-pleasereview

#332 QR Code Scanner Fixes
  src/screens/QrScanner.js
  src/stores/ScannerStore.js
  src/util/decoders.js
Labels: A8-looksgood

#343 Chore: bump 301
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A0-pleasereview, A2-insubstantial

#338 fix: delete account
  src/stores/AccountsStore.js
  src/util/account.js
Labels: A7-looksgoodcantmerge

#344 Bump 3.0.2
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A2-insubstantial

#346 Fix nits
  src/stores/AccountsStore.js
  src/util/account.js
Labels: A2-insubstantial, A8-looksgood
