Repository novasamatech/parity-signer, pull requests merged in 2019-10, with the labels that each got.

#401 chore: bump 308
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A0-pleasereview

#397 chore: remove git restrictions with pre-git and add semantic validator for pr
  .github/semantic.yml
  package.json
  yarn.lock
Labels: A0-pleasereview

#392 feat: Show accounts with unknown network
  src/components/AccountCard.js
  src/components/AccountIcon.js
  src/components/AccountSeed.js
  src/constants.js
  src/screens/AccountBackup.js
  src/screens/AccountDetails.js
  src/screens/AccountEdit.js
  src/screens/AccountList.js
  src/screens/AccountNetworkChooser.js
  src/screens/AccountPin.js
  src/screens/AccountUnlock.js
  src/screens/Loading.js
  src/screens/MessageDetails.js
  src/stores/AccountsStore.js
  src/stores/ScannerStore.js
  src/util/account.js
  src/util/db.js
Labels: A0-pleasereview

#414 fix: use keyboard scroll view for pin input screen
  src/screens/AccountPin.js
Labels: A0-pleasereview, A8-looksgood

#423 chore: lock the version of eslint-babel
  package.json
  yarn.lock
Labels: A8-looksgood

#411 feat: UOS Multipart
  src/screens/QrScanner.js
  src/screens/SignedMessage.js
  src/stores/AccountsStore.js
  src/stores/ScannerStore.js
  src/util/decoders.js
Labels: A8-looksgood

#436 chore: bump 309
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A0-pleasereview, A2-insubstantial

#437 feat: Add kusama dev and update Kusama metadata
  src/components/PayloadDetailsCard.js
  src/constants.js
  src/screens/AccountNetworkChooser.js
  src/util/static-kusama.js
Labels: A8-looksgood

#424 test: Add integration(e2e) test
  .travis.yml
  README.md
  android/app/build.gradle
  android/app/src/androidTest/java/io/parity/signer/DetoxTest.java
  android/build.gradle
  e2e/config.json
  e2e/firstTest.spec.js
  e2e/init.js
  e2e/testIDs.js
  package.json
  scripts/fix-rn-camera-path.sh
  src/components/Button.js
  src/screens/AccountList.js
  src/screens/TermsAndConditions.js
  yarn.lock
Labels: A0-pleasereview

#445 chore: clean build when do `yarn clean`
  package.json
Labels: A8-looksgood

#449 fix: Header and upgrade gradle
  android/build.gradle
  src/App.js
Labels: A0-pleasereview
