Repository novasamatech/parity-signer, pull requests merged in 2019-09, with the labels that each got.

#351 Make release flag implicit
  android/app/build.gradle
Labels: A0-pleasereview

#349 onScan find Address in Store with Appropriate Prefix
  src/stores/ScannerStore.js
  src/util/decoders.js
Labels: A8-looksgood

#309 fix react native warnings
  ios/NativeSigner/EthkeyBridge.m
  src/App.js
  src/components/DataDetails.js
  src/components/QrView.js
  src/components/TextInput.js
Labels: A0-pleasereview

#354 chore: Refactor protocol
  src/screens/AccountNetworkChooser.js
  src/screens/SignedTx.js
  src/screens/TxDetails.js
  src/stores/ScannerStore.js
Labels: A0-pleasereview

#342 chore: mention Kusama and or substrate in the T&Cs
  README.md
  docs/privacy-policy.md.js
  docs/terms-and-conditions.md.js
  src/screens/About.js
Labels: A8-looksgood

#355 Chore: bump 303
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A2-insubstantial, A8-looksgood

#357 chore: show tab correctly
  .editorconfig
Labels: A8-looksgood

#352 Migrate v2
  android/app/build.gradle
  package.json
  src/screens/Loading.js
  src/stores/AccountsStore.js
  src/util/account.js
  src/util/db.js
Labels: A8-looksgood

#359 Chore: bump 304
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A8-looksgood

#361 fix: some code fix catched by eslint
  src/stores/ScannerStore.js
  src/util/array.js
  src/util/decoders.js
Labels: A0-pleasereview

#365 fix: only allow copying seed phrase in dev environment
  src/screens/AccountBackup.js
Labels: A8-looksgood

#366 chore: bump 305
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A2-insubstantial, A8-looksgood

#367 fix: clear account state when changing network
  src/screens/AccountBackup.js
  src/screens/AccountNetworkChooser.js
Labels: A0-pleasereview

#378 chore: remove extra AccountNew padding
  src/screens/AccountNew.js
Labels: A0-pleasereview

#358 fix: Remove substrate dev
  src/constants.js
Labels: A8-looksgood

#379 fix: add pin check
  src/screens/AccountNetworkChooser.js
  src/screens/AccountPin.js
Labels: A8-looksgood

#385 chore: bump 306
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A2-insubstantial

#388 Update readme for Kusama screenshots and tutorials
  README.md
  docs/screenshots.jpg
  docs/screenshots.png
Labels: A2-insubstantial

#377 align height in Account new screen
  src/components/AccountCard.js
  src/components/AccountIconChooser.js
  src/components/Address.js
  src/screens/AccountList.js
Labels: A8-looksgood

#391 chore: bump 307
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A2-insubstantial, A8-looksgood

#396 fix: flexible message field
  src/screens/MessageDetails.js
  src/screens/SignedMessage.js
Labels: A8-looksgood

#395 chore: Use Kusama cc2 genesis hash
  src/constants.js
Labels: A0-pleasereview
