Repository novasamatech/parity-signer, pull requests merged in 2019-11, with the labels that each got.

#453 chore: Eslint now works on root folder
  .eslintignore
  .eslintrc.js
  ReactotronConfig.js
  babel.config.js
  docs/privacy-policy.md.js
  docs/terms-and-conditions.md.js
  e2e/firstTest.spec.js
  e2e/init.js
  e2e/testIDs.js
  index.android.js
  index.ios.js
  index.js
  ios/metro.config.js
  jest-setup.js
  jest.config.js
  metro.config.js
  package.json
Labels: A0-pleasereview, A2-insubstantial

#454 feat: Rust<>JS bindings for Schnorrkel signature verification
  android/app/src/main/java/io/parity/signer/EthkeyBridge.java
  ios/NativeSigner/EthkeyBridge.m
  ios/NativeSigner/EthkeyBridge.swift
  rust/signer/signer.h
  rust/signer/src/lib.rs
  rust/signer/src/sr25519.rs
  rust/signer/src/util.rs
  src/util/native.js
Labels: A0-pleasereview

#455 chore: add rust test to test
  package.json
Labels: A2-insubstantial, A8-looksgood

#456 test: add test arguments for e2e test
  android/app/src/main/java/io/parity/signer/MainActivity.java
  ios/NativeSigner/AppDelegate.m
  src/App.js
Labels: A8-looksgood

#459 chore: update genesis hash for substrate dev
  src/constants.js
Labels: A2-insubstantial, A8-looksgood

#462 chore: bump 4.0.0
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A2-insubstantial, A8-looksgood

#463 fix: remove version in "About" to fix CI
  src/screens/About.js
Labels: A0-pleasereview

#475 fix: prevent signing with unknown sender
  src/stores/AccountsStore.js
  src/stores/ScannerStore.js
Labels: A0-pleasereview

#477 chore: renaming to seedPhrase when phrase is used
  .gitignore
  specs/util/identitiesUtils.spec.js
  src/screens/AccountNetworkChooser.js
  src/screens/IdentityBackup.js
  src/screens/IdentityManagement.js
  src/screens/MessageDetails.js
  src/screens/PathDerivation.js
  src/screens/PathDetails.js
  src/screens/TxDetails.js
  src/stores/AccountsStore.js
  src/stores/ScannerStore.js
  src/stores/types.js
  src/util/identitiesUtils.js
  src/util/navigationHelpers.js
Labels: A0-pleasereview

#471 fix: current Identity screen after deletion
  src/components/IdentitiesSwitch.js
  src/screens/AccountNetworkChooser.js
  src/stores/AccountsStore.js
Labels: A0-pleasereview

#467 fix: seed recovery validation and unlock fix
  specs/util/suri.spec.js
  src/screens/AccountRecover.js
  src/screens/IdentityNew.js
  src/util/account.js
  src/util/alertUtils.js
  src/util/debounce.js
  src/util/suri.js
Labels: A0-pleasereview
