Repository novasamatech/parity-signer, pull requests merged in 2019-12, with the labels that each got.

#481 fix: Support cc3
  package.json
  specs/util/decoders.spec.js
  specs/util/identitiesUtils.spec.js
  specs/util/units.spec.js
  src/App.js
  src/components/PayloadDetailsCard.js
  src/constants.js
  src/util/decoders.js
  src/util/static-kusama.js
  yarn.lock
Labels: A7-looksgoodtestsfail

#480 feat: dynamically bind gensisHash to accountId
  e2e/identityManipulation.spec.js
  e2e/mock.js
  specs/util/identitiesUtils.spec.js
  src/components/AccountCard.js
  src/components/AccountIcon.js
  src/components/AccountPrefixedTitle.js
  src/components/CompatibleCard.js
  src/components/IdentitiesSwitch.js
  src/components/PathCard.js
  src/components/UnknownAccountWarning.js
  src/constants.js
  src/screens/AccountDetails.js
  src/screens/AccountEdit.js
  src/screens/AccountNetworkChooser.js
  src/screens/AccountNew.js
  src/screens/AccountRecover.js
  src/screens/LegacyAccountBackup.js
  src/screens/LegacyAccountList.js
  src/screens/Loading.js
  src/screens/PathDetails.js
  src/screens/PathsList.js
  src/stores/AccountsStore.js
  src/stores/ScannerStore.js
  src/stores/types.js
  src/util/account.js
  src/util/db.js
  src/util/identitiesUtils.js
  src/util/navigationHelpers.js
Labels: A8-looksgood

#483 chore: Bump to 4.0.4
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A2-insubstantial, A8-looksgood

#492 docs: update screenshot
  docs/screenshots.png
Labels: A0-pleasereview, A2-insubstantial

#491 fix: modal block scan button
  src/components/IdentitiesSwitch.js
Labels: A0-pleasereview

#498 fix: error with new recipient account
  src/stores/ScannerStore.js
Labels: A8-looksgood

#495 fix: use Metadata properly, not with the wrapped Metadata
  package.json
  specs/util/decoders.spec.js
  specs/util/units.spec.js
  src/components/PayloadDetailsCard.js
  yarn.lock
Labels: A8-looksgood

#500 test: add eslint-plugin-import validation
  .eslintrc.js
  package.json
  src/App.js
  src/screens/SignedMessage.js
  src/screens/SignedTx.js
  src/util/native.js
  yarn.lock
Labels: A8-looksgood

#499 style: move scan button to top bar
  e2e/identityManipulation.spec.js
  e2e/testIDs.js
  src/components/SecurityHeader.js
  src/screens/AccountNetworkChooser.js
  src/screens/LegacyAccountList.js
  src/screens/PathsList.js
Labels: A8-looksgood

#501 docs: add debug unit test command into package.json
  README.md
  package.json
Labels: A2-insubstantial, A8-looksgood

#494 feat: enable create root account under a network
  specs/util/identitiesUtils.spec.js
  src/components/AccountCard.js
  src/components/AccountIcon.js
  src/components/AccountIconChooser.js
  src/components/PathCard.js
  src/components/ScreenHeading.js
  src/screens/AccountDetails.js
  src/screens/AccountNetworkChooser.js
  src/screens/PathDerivation.js
  src/screens/PathDetails.js
  src/screens/PathsList.js
  src/stores/AccountsStore.js
  src/util/alertUtils.js
  src/util/identitiesUtils.js
  src/util/navigationHelpers.js
  src/util/regex.js
Labels: A8-looksgood

#505 fix: extra height, focus, suggestions in text input
  src/components/AccountSeed.js
  src/components/ButtonNewDerivation.js
  src/screens/IdentityNew.js
  src/screens/IdentityPin.js
  src/screens/PathDerivation.js
Labels: A8-looksgood

#504 chore: Update terms-and-conditions.md.js
  docs/terms-and-conditions.md.js
Labels: A8-looksgood

#497 feat: Enable create custom path
  e2e/identityManipulation.spec.js
  e2e/testIDs.js
  specs/util/identitiesUtils.spec.js
  src/components/CompatibleCard.js
  src/components/IdentitiesSwitch.js
  src/components/PathCard.js
  src/components/PopupMenu.js
  src/components/ScreenHeading.js
  src/components/SecurityHeader.js
  src/components/UnknownAccountWarning.js
  src/constants.js
  src/screens/AccountNetworkChooser.js
  src/screens/MessageDetails.js
  src/screens/PathDerivation.js
  src/screens/PathDetails.js
  src/screens/PathsList.js
  src/screens/QrScanner.js
  src/screens/SignedTx.js
  src/screens/TxDetails.js
  src/stores/AccountsStore.js
  src/stores/ScannerStore.js
  src/util/account.js
  src/util/identitiesUtils.js
  src/util/navigationHelpers.js
Labels: A8-looksgood

#506 chore: Bump 4.0.5
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A2-insubstantial, A8-looksgood
