Repository novasamatech/parity-signer, pull requests merged in 2019-02, with the labels that each got.

#212 Ethereum message sign
  src/App.js
  src/screens/AccountUnlock.js
  src/screens/MessageDetails.js
  src/screens/QrScanner.js
  src/screens/SignedMessage.js
  src/stores/AccountsStore.js
  src/stores/ScannerStore.js
  src/util/message.js
Labels: A0-pleasereview

#220 README: Add info on Android Studio and Troubleshooting
  README.md
Labels: A2-insubstantial

#209 fix: Relates to #140. Update React Native to 0.56
  .babelrc
  .travis.yml
  babel.config.js
  package.json
Labels: A8-looksgood

#226 Tbaut remove tab navigation
  package-lock.json
  package.json
  src/App.js
  src/components/TabBarBottom.js
  src/screens/AccountList.js
  src/screens/AccountPin.js
  src/screens/AccountUnlock.js
  src/screens/Loading.js
  src/screens/SignedMessage.js
  src/screens/SignedTx.js
  src/screens/TxDetails.js
Labels: A0-pleasereview, M7-UX
