Repository novasamatech/parity-signer, pull requests merged in 2020-01, with the labels that each got.

#511 fix: add custom scroll view with custom scroll bar
  src/components/CustomScrollView.js
  src/screens/About.js
  src/screens/PrivacyPolicy.js
  src/screens/TermsAndConditions.js
Labels: A8-looksgood

#514 chore: fix navigation after path deletion
  src/screens/PathDetails.js
Labels: A2-insubstantial, A8-looksgood

#515 feat: add support for 12 mnemonic option
  android/app/src/main/java/io/parity/signer/EthkeyBridge.java
  ios/NativeSigner/EthkeyBridge.m
  ios/NativeSigner/EthkeyBridge.swift
  rust/signer/signer.h
  rust/signer/src/lib.rs
  src/components/Button.js
  src/screens/IdentityBackup.js
  src/util/native.js
Labels: A0-pleasereview

#520 fix: pin input text and return button
  e2e/e2eUtils.js
  e2e/identityManipulation.spec.js
  src/screens/IdentityNew.js
  src/screens/IdentityPin.js
  src/screens/PathDerivation.js
Labels: A0-pleasereview

#516 feat: enable path derivation from existed path card
  specs/util/identitiesUtils.spec.js
  src/screens/AccountDetails.js
  src/screens/AccountNetworkChooser.js
  src/screens/PathDerivation.js
  src/screens/PathDetails.js
  src/screens/PathManagement.js
  src/screens/PathsList.js
  src/util/alertUtils.js
Labels: A0-pleasereview, P2-asap

#527 chore: Bump Polkadot api
  package.json
  yarn.lock
Labels: A0-pleasereview

#523 fix: display soft derivation custom path
  specs/util/identitiesUtils.spec.js
  src/screens/PathsList.js
  src/util/identitiesUtils.js
  src/util/regex.js
Labels: A0-pleasereview, P2-asap

#526 chore: Update metadata and kusama dev hash
  package.json
  src/constants.js
  src/util/static-kusama.js
  yarn.lock
Labels: A0-pleasereview

#528 chore: bump Signer to v4.0.6
  android/app/build.gradle
  ios/NativeSigner/Info.plist
  package.json
Labels: A0-pleasereview, A2-insubstantial

#531 fix: add whitespace after tapping the suggestion text
  src/components/AccountSeed.js
  src/screens/IdentityNew.js
  src/util/account.js
Labels: A0-pleasereview
