Repository novasamatech/parity-signer, pull requests merged in 2020-04, with the labels that each got.

#580 feat: sign with seed reference
  android/app/src/main/java/io/parity/signer/EthkeyBridge.java
  ios/NativeSigner/EthkeyBridge.m
  ios/NativeSigner/EthkeyBridge.swift
  rust/signer/signer.h
  rust/signer/src/lib.rs
  rust/signer/src/util.rs
  src/utils/native.ts
Labels: A8-looksgood

#575 refactor: regroup the paths into their own network.
  src/components/PathCard.tsx
  src/constants/networkSpecs.ts
  src/screens/AccountNetworkChooser.tsx
  src/screens/PathDerivation.tsx
  src/screens/PathDetails.tsx
  src/screens/PathsList.tsx
  src/stores/AccountsStore.ts
  src/types/networkSpecsTypes.ts
  src/utils/account.ts
  src/utils/identitiesUtils.ts
  test/unit/specs/util/identitiesUtils.spec.ts
Labels: A8-looksgood

#587 chore: upgrade prettier related packages
  package.json
  src/components/NetworkButton.tsx
  yarn.lock
Labels: A2-insubstantial

#586 fix: sync extend types with polkadot.js/api
  package.json
  src/stores/RegistriesStore.ts
  test/unit/specs/util/decoders.spec.ts
  yarn.lock
Labels: A8-looksgood

#583 fix: seed reference wrapper
  src/utils/native.ts
  src/utils/seedRefHooks.ts
Labels: A0-pleasereview

#572 docs: update docs for 32-bit apple architecture
  README.md
  rust/signer/Makefile
  setup_macos.sh
Labels: A0-pleasereview, A2-insubstantial

#590 feat: enable generate address with seed
  android/app/src/main/java/io/parity/signer/EthkeyBridge.java
  ios/NativeSigner/EthkeyBridge.m
  ios/NativeSigner/EthkeyBridge.swift
  package.json
  rust/signer/signer.h
  rust/signer/src/lib.rs
  src/utils/native.ts
Labels: A8-looksgood

#594 fix: identities switch bottom shadow blocks button
  src/components/IdentitiesSwitch.tsx
  src/utils/seedRefHooks.ts
Labels: A0-pleasereview

#591 feat: add Centrifuge Mainnet and Centrifuge Testnet Amber
  ios/assets/res/img/logos/centrifuge-chain.png
  ios/assets/res/img/logos/centrifuge-chain@2x.png
  ios/assets/res/img/logos/centrifuge-chain@3x.png
  res/img/logos/centrifuge-chain.png
  res/img/logos/centrifuge-chain@2x.png
  res/img/logos/centrifuge-chain@3x.png
  src/constants/networkMetadata.ts
  src/constants/networkSpecs.ts
  src/stores/RegistriesStore.ts
  src/utils/identitiesUtils.ts
Labels: A0-pleasereview

#599 chore: add helper function in android
  android/app/src/main/java/io/parity/signer/EthkeyBridge.java
Labels: A0-pleasereview

#597 feat: error handling/report in rust lib
  android/app/src/main/java/io/parity/signer/EthkeyBridge.java
  ios/NativeSigner.xcodeproj/project.pbxproj
  ios/NativeSigner/EthkeyBridge.swift
  ios/NativeSigner/String.swift
  ios/Podfile.lock
  package.json
  rust/signer/Cargo.lock
  rust/signer/Cargo.toml
  rust/signer/signer.h
  rust/signer/src/eth.rs
  rust/signer/src/export/android/arg.rs
  rust/signer/src/export/android/mod.rs
  rust/signer/src/export/android/ret.rs
  rust/signer/src/export/android/util.rs
  rust/signer/src/export/ios/arg.rs
  rust/signer/src/export/ios/mod.rs
  rust/signer/src/export/ios/ret.rs
  rust/signer/src/export/mod.rs
  rust/signer/src/lib.rs
  rust/signer/src/result.rs
  rust/signer/src/sr25519.rs
  rust/signer/src/util.rs
Labels: A9-buythatmanabeer

#598 chore: add chain metadata
  src/utils/identitiesUtils.ts
Labels: A0-pleasereview, A2-insubstantial

#589 feat: support pinless signing when user already input pin recently
  ios/NativeSigner/EthkeyBridge.m
  package.json
  src/App.tsx
  src/components/IdentitiesSwitch.tsx
  src/modules/main/components/NetworkSelector.tsx
  src/modules/main/components/NoCurrentIdentity.tsx
  src/modules/main/components/OnBoading.tsx
  src/modules/main/screens/Main.tsx
  src/modules/main/styles.ts
  src/modules/unlock/screens/PinUnlock.tsx
  src/modules/unlock/screens/PinUnlockWithPassword.tsx
  src/screens.tsx
  src/screens/AccountNetworkChooser.tsx
  src/screens/IdentityBackup.tsx
  src/screens/IdentityManagement.tsx
  src/screens/IdentityNew.tsx
  src/screens/MessageDetails.tsx
  src/screens/PathDerivation.tsx
  src/screens/PathDetails.tsx
  src/screens/TxDetails.tsx
  src/stores/AccountsStore.ts
  src/stores/ScannerStore.ts
  src/stores/SeedRefStore.tsx
  src/types/identityTypes.ts
  src/types/routes.ts
  src/utils/HOC.tsx
  src/utils/account.ts
  src/utils/alertUtils.ts
  src/utils/errors.ts
  src/utils/identitiesUtils.ts
  src/utils/native.ts
  src/utils/navigationHelpers.ts
  src/utils/seedRefHooks.ts
  src/utils/suri.ts
  test/e2e/specs/identityManipulation.spec.ts
  test/e2e/specs/passwordedAccount.spec.ts
  test/e2e/specs/signing.spec.ts
  test/e2e/testIDs.ts
  test/e2e/utils.ts
  yarn.lock
Labels: A0-pleasereview

#601 fix: prevent back on network choser android
  package.json
  src/modules/main/components/NetworkSelector.tsx
Labels: A0-pleasereview
