Repository novasamatech/parity-signer, pull requests merged in 2022-06, with the labels that each got.

#1066 fix: android: start over has to reset scanning
  android/app/src/main/java/io/parity/signer/SignerScreen.kt
  android/app/src/main/java/io/parity/signer/models/Camera.kt
  android/app/src/main/java/io/parity/signer/screens/ScanScreen.kt
Labels: android

#1065 fix: android: scan screen always on
  android/app/src/main/java/io/parity/signer/screens/ScanScreen.kt
Labels: android

#1054 fix: android filter out non qr barcodes
  android/app/src/main/java/io/parity/signer/screens/NewAddressScreen.kt
  android/app/src/main/java/io/parity/signer/screens/RecoverSeedName.kt
  android/app/src/main/java/io/parity/signer/screens/RecoverSeedPhrase.kt
  android/app/src/main/java/io/parity/signer/screens/ScanScreen.kt
  android/app/src/main/java/io/parity/signer/screens/SeedManager.kt
  android/app/src/main/java/io/parity/signer/screens/SelectSeedForBackup.kt
Labels: backend, android

#1083 fix: load_metadata update: additional name check
  rust/db_handling/src/helpers.rs
  rust/definitions/src/error_signer.rs
  rust/definitions/src/test_all_errors_signer.rs
  rust/transaction_parsing/src/holds.rs
  rust/transaction_parsing/src/load_metadata.rs
Labels: security, blocks next release

#1088 fix: check same name in add_specs, few nits
  rust/db_handling/src/helpers.rs
  rust/db_handling/src/identities.rs
  rust/db_handling/src/tests.rs
  rust/definitions/src/error_signer.rs
  rust/definitions/src/history.rs
  rust/definitions/src/keyring.rs
  rust/definitions/src/metadata.rs
  rust/definitions/src/test_all_errors_signer.rs
  rust/signer/src/signer.udl
  rust/transaction_parsing/src/add_specs.rs
  rust/transaction_parsing/src/load_metadata.rs
  rust/transaction_parsing/src/tests.rs
Labels: security, blocks next release

#1124 fix: paths to ndk were fixed in upstream
  android/app/build.gradle
  android/build.gradle
Labels: building, android

#1119 refactor: integration tests separated, optional path hot db
  rust/db_handling/src/cold_default.rs
  rust/db_handling/src/lib.rs
  rust/db_handling/src/manage_history.rs
  rust/db_handling/src/tests.rs
  rust/db_handling/tests/tests.rs
  rust/generate_message/src/lib.rs
Labels: testing, backend

#989 chore: adds cargo deny workflow
  .github/workflows/rust-cargo-deny.yml
  rust/deny.toml
Labels: building, security

#1056 docs: uos interpretation
  docs/src/development/UOS.md
Labels: documentation

#1132 docs: remove redundant docs hotfix
  rust/generate_message/pseudo_instruction.md
Labels: documentation

#1106 fix: derivation import: do not try to select seed if there are no seeds
  rust/definitions/src/error_signer.rs
  rust/definitions/src/test_all_errors_signer.rs
  rust/navigator/src/navstate.rs
  rust/navigator/src/screens.rs
Labels: security, backend, UX

#1096 chore: polkadot9220 update
  rust/defaults/release_metadata/kusama9200
  rust/defaults/release_metadata/kusama9230
  rust/defaults/release_metadata/polkadot9190
  rust/defaults/release_metadata/polkadot9220
Labels: blocks next release
