Repository novasamatech/parity-signer, pull requests merged in 2022-03, with the labels that each got.

#937 fix: ios: wipe even if database not found
  ios/NativeSigner/Models/RustNative.swift
Labels: blocks next release

#924 fix: backend: increase presented expected frames count
  android/app/src/main/java/io/parity/signer/components/ScanProgressBar.kt
  android/app/src/main/java/io/parity/signer/models/Camera.kt
  android/app/src/main/java/io/parity/signer/screens/ScanScreen.kt
  ios/NativeSigner/Components/CameraView.swift
  ios/NativeSigner/Components/Canary.swift
  ios/NativeSigner/Models/CameraService.swift
  rust/qr_reader_phone/src/lib.rs
Labels: blocks next release

#923 style: ios: landing alert design
  ios/NativeSigner/Screens/LandingView.swift
Labels: blocks next release

#932 fix: more clear error message for unsuitable metadata
  rust/definitions/src/error.rs
  rust/definitions/src/test_all_errors_signer.rs
  rust/navigator/src/tests.rs
  rust/parser/src/decoding_older.rs
  rust/parser/src/lib.rs
  rust/transaction_parsing/src/parse_transaction.rs
  rust/transaction_parsing/src/tests.rs
Labels: blocks next release

#954 style: ios update web3 font
  ios/NativeSigner/Fonts/Web3-Regular.otf
Labels: blocks next release

#968 fix: android: fix seedname base64 in new address and recover seed
  android/app/src/main/java/io/parity/signer/screens/NewAddressScreen.kt
  android/app/src/main/java/io/parity/signer/screens/RecoverSeedName.kt
Labels: blocks next release

#970 docs: add link to FAQ
  docs/src/README.md
  docs/src/SUMMARY.md
Labels: documentation

#972 fix: backend: check that message is completely decoded
  rust/transaction_parsing/src/message.rs
  rust/transaction_parsing/src/tests.rs
Labels: blocks next release

#975 build: android: build rust code with gradle
  android/app/build.gradle
  android/app/src/main/java/io/parity/signer/MainActivity.kt
  android/build.gradle
  rust/db_handling/src/lib.rs
  rust/generate_message/src/lib.rs
  rust/generate_message/src/parser.rs
  rust/os-specific-lock/android/Cargo.lock
  rust/os-specific-lock/ios/Cargo.lock
  rust/signer/android-hack/Cargo.toml
  rust/signer/build.rs
  rust/signer/ios-hack/Cargo.toml
  scripts/build.sh
  scripts/switch_to_android.sh
Labels: building, android

#982 chore: move android CI from gitlab to GHA
  .github/workflows/android-app.yml
  .gitlab-ci.yml
  bitrise.yml
Labels: CI, android
